config/routes.rb
Rails.application.routes.draw do
  resources :exhibit_digital_objects
  resources :exhibits
  resources :user_digital_objects
  devise_for :users
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'my_objects', to: 'users#my_objects'
  get 'search_dpla', to: 'digital_objects#search'
end

app/models/exhibit.rb
class Exhibit < ApplicationRecord
  belongs_to :user
  has_many :exhibit_digital_objects, -> { order(object_order: "asc") }, inverse_of: :exhibit, dependent: :destroy
  has_many :digital_objects, -> { select('digital_objects.*, exhibit_digital_objects.note as note, exhibit_digital_objects.object_order as object_order') }, through: :exhibit_digital_objects
  accepts_nested_attributes_for :exhibit_digital_objects, reject_if: :all_blank, allow_destroy: true
  has_rich_text :description_content
end

app/controllers/exhibits_controller.rb
class ExhibitsController < ApplicationController
  before_action :set_exhibit, only: %i[ show edit update destroy ]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /exhibits or /exhibits.json
  def index
    @exhibits = Exhibit.all
  end

  # GET /exhibits/1 or /exhibits/1.json
  def show
  end

  # GET /exhibits/new
  def new
    @exhibit = Exhibit.new
    @digital_objects = current_user.digital_objects
    @objects_in_exhibit = current_user.digital_objects.where(id: @exhibit.digital_objects.ids)
    @objects_not_in_exhibit = current_user.digital_objects.where.not(id: @exhibit.digital_objects.ids)
  end

  # GET /exhibits/1/edit
  def edit
    @exhibit.user = current_user
    @digital_objects = current_user.digital_objects
    @objects_in_exhibit = current_user.digital_objects.where(id: @exhibit.digital_objects.ids)
    @objects_not_in_exhibit = current_user.digital_objects.where.not(id: @exhibit.digital_objects.ids)
  end

  # POST /exhibits or /exhibits.json
  def create
    @exhibit = Exhibit.new(exhibit_params)
    @exhibit.user = current_user
    @digital_objects = current_user.digital_objects
    @objects_in_exhibit = current_user.digital_objects.where(id: @exhibit.digital_objects.ids)
    @objects_not_in_exhibit = current_user.digital_objects.where.not(id: @exhibit.digital_objects.ids)
    respond_to do |format|
      if @exhibit.save
        format.html { redirect_to exhibit_url(@exhibit), notice: "Exhibit was successfully created." }
        format.json { render :show, status: :created, location: @exhibit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exhibit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibits/1 or /exhibits/1.json
  def update
    respond_to do |format|
      if @exhibit.update(exhibit_params)
        format.html { redirect_to exhibit_url(@exhibit), notice: "Exhibit was successfully updated." }
        format.json { render :show, status: :ok, location: @exhibit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exhibit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibits/1 or /exhibits/1.json
  def destroy
    @exhibit.destroy

    respond_to do |format|
      format.html { redirect_to exhibits_url, notice: "Exhibit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibit
      @exhibit = Exhibit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exhibit_params
      params.require(:exhibit).permit(:title, :id, :description, :description_content, digital_object_ids: [], digital_object_attributes: [:note], exhibit_digital_objects_attributes: [:id, :note, :content, :object_order, :digital_object_id, :exhibit_id, :_destroy])
    end

    def require_same_user
      if current_user != @exhibit.user
        flash[:alert] = "You can only modify your own articles."
        redirect_to @article
      end
    end

end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
end

app/views/exhibits/_form.html.erb
<%= render 'shared/errors', obj: @exhibit %>
<div class="container">
    <div class="row justify-content-center">
    <div class="col-10">
        <%= form_with(model: @exhibit, class: "shadow p-3 mb-3 bg-light rounded") do |f| %>
            <div class="form-group row p-3">
                <div class="col-2">
                <%= f.label :title, class: "col-form-label" %>
                </div>
                <div class="col-10">
                <%= f.text_field :title, class: "form-control shadow rounded" %>
                </div>
            </div>

            <div class="form-group row p-3">
                <div class="col-2">
                <%= f.label :description, class: "col-form-label" %>
                </div>
                <div class="col-10">
                <%= f.rich_text_area :description_content, rows: 10, class: "form-control shadow rounded" %>
                </div>
            </div>

            <div class="form-group row p-3">
                <div class="col-2">
                <%= f.label :digital_objects, class: "col-form-label" %>
                </div>
                <div class="col-10">

                <h3>Objects to Add</h3>
                <p>Drag objects to re-order</p>
                <div id='digital_objects' class="sort accordion" >
                    
                    <%= f.fields_for :exhibit_digital_objects do |obj| %>
                    <%= render 'digital_objects/obj_fields', :f => obj %>
                    <% end %>
                    <div class='links'>
                    <%= link_to_add_association 'Add Object', f, :exhibit_digital_objects, partial: 'digital_objects/obj_fields', class: "btn btn-primary mt-2" %>
                    </div>
                </div>
                </div>
            </div>
            
            <div class="form-group row p-3 justify-content-center">
                <%= f.submit class: "btn btn-outline-dark btn-lg" %>
            </div>
        </div>
        <% end %>
        <script>
      digital_object_json = {
        <% @digital_objects.each do |obj|%>
            <%= obj.id %> : {
              "title": "<%= obj.title %>",
              "description": "<%= obj.description %>",
              "img_id": "<%= obj.object %>",
              "source": "<%= obj.dataProvider %>"
          }, 
        <% end %>
      };
    </script>
        <%= javascript_pack_tag 'sort-objects' %>
    </div>
    </div>
</div>

app/views/exhibits/edit.html.erb
<h1>Editing Exhibit</h1>

<%= render 'form', exhibit: @exhibit %>

<%= link_to 'Show', @exhibit %> |
<%= link_to 'Back', exhibits_path %>

app/views/exhibits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exhibits</h1>
<div class="container">
  <div class="mx-auto d-flex justify-content-around flex-wrap" >

    <% @exhibits.each do |exhibit| %>

      <div class="card col-md-3 col-sm-5 text-center mb-4 mx-2 shadow rounded text-center">
          <div class="item-discussion card-body pb-4 mx-2">
               <h2 class="h3"><%= exhibit.title %></h2>
                  <p><%= exhibit.description %></p>
                  <%= link_to 'View', exhibit_path(exhibit), class: "btn btn-outline-secondary btn-sm my-2" %>
                  <figure class="figure shadow-sm p-4">
                    <% if exhibit.digital_objects.any? %>
                      <img src="https://dp.la/thumb/<%= exhibit.digital_objects.first.object %>" class="figure-img img-fluid rounded" alt="<%= exhibit.digital_objects.first.title %>" onerror="this.onerror=null;this.src='noimg.svg';">
                    <% end %>
                    <figcaption class="figure-caption">
                        <p><%= exhibit.digital_objects.first.title %> | <%= exhibit.digital_objects.first.dataProvider %><br>
                        <a target="_blank" href="<%= exhibit.digital_objects.first.sourceLink %>" class="">View Original</a></p>
                    </figcaption>
                  </figure><br>
                  <% if exhibit.user == current_user %>
                    <%= link_to 'Edit', edit_exhibit_path(exhibit) %> | <%= link_to 'Destroy', exhibit, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% end %>
          </div>
      </div>
    <% end %>
</div>
</div>
<br>

<%= link_to 'New Exhibit', new_exhibit_path %>

app/views/exhibits/new.html.erb
<h1>New Exhibit</h1>

<%= render 'form', exhibit: @exhibit %>

<%= link_to 'Back', exhibits_path %>

app/views/exhibits/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="mx-auto d-flex justify-content-around flex-wrap" >
    <div class="card shadow col-sm-11  mb-4 shadow rounded">
      <div class="card-header">
        <h1>
          <%= @exhibit.title %>
        </h1>
      </div>
      <div class="card-body">
        <p>
          <%= @exhibit.description_content %>
        </p>
      </div>
    </div>

    <% if @exhibit.digital_objects.any? %>
        <%= render @exhibit.digital_objects.sort_by { |digital_object| digital_object.object_order } %>
    <% end %>
  </div>

  <%= link_to 'Edit', edit_exhibit_path(@exhibit) %> |
  <%= link_to 'Back', exhibits_path %>
</div>