config/routes.rb
Rails.application.routes.draw do
  resources :exhibit_digital_objects
  resources :exhibits
  resources :user_digital_objects
  devise_for :users
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'my_objects', to: 'users#my_objects'
  get 'search_dpla', to: 'digital_objects#search'
end

app/models/user.rb
class User < ApplicationRecord

  has_many :user_digital_objects
  has_many :digital_objects, through: :user_digital_objects
  has_many :exhibits, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_objects
    @saved_collection = current_user.digital_objects
  end
end

app/views/users/_result.html.erb
<% if @collection %>
    <div class="modal fade" id="searchResults" tabindex="-1" aria-labelledby="searchResultModal" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable modal-fullscreen-md-down">
        <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title h5" id="searchResultModal">Search Results</h3>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            
        <div>
                <% if @prevpage > 0 %>
                    <%= link_to "Previous page", search_dpla_path(:query => @query, :page => @prevpage), method: :get, class: "btn btn-info btn-lg me-2" %>
                <% end %>
                <%= link_to "Next page", search_dpla_path(:query => @query, :page => @nextpage),method: :get, class: "btn btn-info btn-lg" %>
            </div>
                <% @collection.documents.each do |document| %>
                <div class="card card-header mt-4 results-inline">
                    <span class="title"><strong>Title: </strong> <%= document.title[0] %></span>
                    <span class="description"><strong>Description: </strong> <%= document.description.join(" -- ") if document.description %></span>
                    <span class="source"><strong>Source: </strong> <%= document.source['name'] %></span>
                    <span class="image">
                        <img class="img-fluid img-thumbnail" src="https://dp.la/thumb/<%= document.id %>"<br>
                        <a target="_blank" href="<%= document.url %>">View Original</a>
                    </span>
                    <%= link_to 'Add to collection', user_digital_objects_path(user: current_user, object_id: document.id),
                            class: "btn btn-success ms-2", method: :post %>
                </div>
                <% end %>
            <div>
                <% if @prevpage > 0 %>
                    <%= link_to "Previous page", search_dpla_path(:query => @query, :page => @prevpage), method: :get, class: "btn btn-info btn-lg mt-2 me-2" %>
                <% end %>
                <%= link_to "Next page", search_dpla_path(:query => @query, :page => @nextpage),method: :get, class: "btn btn-info btn-lg mt-2" %>
            </div> 


        </div>
        </div>
    </div>
    </div>
    <!--<script><%= render 'users/result.js', formats: :js %></script>-->
<% end %>

app/views/users/_result.js.erb
var resultsModal = new bootstrap.Modal(document.getElementById('searchResults'), {
  focus: true
});
resultsModal.show();

app/views/users/my_objects.html.erb
<h1 class="mt-4">My Digital Objects</h1>
<hr>
<div class="search-area">
    <h2 class="h3">Search for Digital Objects</h2>
    <%= form_tag search_dpla_path, method: :get do%>
        <div class="form-group row">
            <div class="col-sm-10">
                <%= text_field_tag :query, params[:query], placeholder: "Search the DPLA", autofocus: true, class: "form-control form-control-lg" %>
                <%= hidden_field_tag 'page', params[:page].present? ? params[:page] : 1 %>
            </div>
            <div class="col-sm-2">
            <%= button_tag type: :submit, class: "btn btn-success btn-lg" do %>
                <%= fa_icon 'search', text: "Search", class: "h3" %>
            <% end %>
            </div>
        </div>
    <% end %>
</div>
<%= render 'users/result' %>
<%= render 'digital_objects/list' %>