config/routes.rb
Rails.application.routes.draw do
  resources :exhibit_digital_objects
  resources :exhibits
  resources :user_digital_objects
  devise_for :users
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'my_objects', to: 'users#my_objects'
  get 'search_dpla', to: 'digital_objects#search'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container">
    <h1>Exhibit Builder</h1>

    <p>Welcome to Exhibit Builder.  All the exhibits on this site were made using items from the <a href="https://dp.la">Digital Public Library of America</a>, which aggregates existing digital collections from around the country.<p>
    <div class="mt-4 mb-4 text-center">
    <%= link_to "View Exhibits", exhibits_path, class: "btn btn-outline-success mb-2" %><br>
    <% if logged_in?%>
        <%= link_to "Search the DPLA", my_objects_path, class: "btn btn-outline-success mb-2" %><br>
        <%= link_to "Create a New Exhibit", new_exhibit_path, class: "btn btn-outline-success mb-2" %><br>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger mb-2" %>
    <% end %>
    <% if !logged_in? %>
        <p>Want to create  your own exhibits?</p>
        <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-success mb-2" %><br>
        <%= link_to "Create an Account",  new_user_registration_path, class: "btn btn-outline-success mb-2" %><br>
    <% end %>
    </div>
    <p>This page was created using Ruby on Rails</p>
</div>