config/routes.rb
Rails.application.routes.draw do
  resources :exhibit_digital_objects
  resources :exhibits
  resources :user_digital_objects
  devise_for :users
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'my_objects', to: 'users#my_objects'
  get 'search_dpla', to: 'digital_objects#search'
end

app/models/digital_object.rb
class DigitalObject < ApplicationRecord

  has_many :user_digital_objects
  has_many :users, through: :user_digital_objects
  has_many :exhibit_digital_objects, inverse_of: :digital_object, dependent: :destroy
  has_many :exhibits, through: :exhibit_digital_objects
  accepts_nested_attributes_for :exhibit_digital_objects

  def self.search(query, page)
    begin
      @documents_collection = DPLibrary::DocumentCollection.new({q: query, page: page})
    rescue => exception
      return nil
    end
  end

  def self.get_new(object_id)
    @documents_collection = DPLibrary::DocumentCollection.new({id: object_id})
    digital_object = @documents_collection.documents.first
    begin
      new(object: digital_object.id, description: digital_object.description ? digital_object.description.join(" -- ") : "", title: digital_object.title[0], creator: digital_object.creator, dataProvider: digital_object.source['name'] ? digital_object.source['name'] : digital_object.source, sourceLink: digital_object.url, format: digital_object.format)
    rescue => exception
      return nil
    end
  end

  def self.check_db(object_id)
    where(object: object_id).first
  end


end

app/controllers/digital_objects_controller.rb
class DigitalObjectsController < ApplicationController

  def search
    @saved_collection = current_user.digital_objects
    if (!params[:query].blank?)
      page = params[:page].present? ? params[:page] : 1;
      @nextpage = page.to_i + 1;
      @prevpage = page.to_i - 1;
      @query = params[:query]
      @collection = DigitalObject.search(@query, page)
      if (@collection)
        render 'users/my_objects'
      else
        flash[:alert] = "Your search returned no results."
        redirect_to my_objects_path
      end
    else
      flash[:alert] = "Please enter a search term."
        redirect_to my_objects_path
    end
  end

  def show
    @saved_collection = current_user.digital_objects
  end

end

app/views/digital_objects/_digital_object.html.erb
<div class="card col-md-5 col-sm-10 text-center mb-4 shadow rounded">
    <div class="card-img-top pt-4">
    <figure class="figure p-4 shadow-sm">
        <img src="https://dp.la/thumb/<%= digital_object.object %>" class="figure-img img-fluid rounded" alt="<%= digital_object.title %>" onerror="this.onerror=null;this.src='noimg.svg';">
        <figcaption class="figure-caption">
            <h2 class="h5"><%= digital_object.title %></h2>
            <%= digital_object.dataProvider %><br>
            <a target="_blank" href="<%= digital_object.sourceLink %>" class="btn btn-outline-secondary btn-sm my-2">View Original</a>
        </figcaption>
    </figure>
    </div>
    <div class="item-discussion card-body pb-4 mx-2 text-start">
        <%= digital_object.exhibit_digital_objects.where(exhibit_id: @exhibit).first.content  %>
    </div>
</div>

app/views/digital_objects/_digital_object_fields.html.erb
<% if dof.object %>
<% dof.object.each do |dobj|  %>
<div class="row">
    <div class="col-sm-2">
        <img class="img-fluid img-thumbnail" src="https://dp.la/thumb/<%= dobj.object %>"/>
    </div>
    <div class="col-sm-10">
        <%= dobj.title %> - <td ><%= dobj.dataProvider %> - <%= dobj.description %>
    </div>
</div>
<div class="form-group row p-3">
    <% f.object.exhibit_digital_objects.where(digital_object_id: dobj.id).ids %>
        <%# <!--<div class="col-2">
        <%= f.label :exhibit_digital_objects_attributes[f.object.exhibit_digital_objects.where(digital_object_id: dobj.id).ids.first][:note], class: "col-form-label" %>-->
        <!--</div>--> %>
        <%= f.fields_for :exhibit_digital_objects, f.object.exhibit_digital_objects.where(digital_object_id: dobj.id) do |newlink| %>
             <%= newlink.label :note %>
             <%= newlink.text_field :note %>
        <% end %>
</div>
<% end %>
<% end %>

app/views/digital_objects/_list.html.erb
<% if @saved_collection && !@saved_collection.empty?%>
<h2 class="mt-4">Saved Collection</h2>
<div class="row col-10 mt-4">
    <table class="table table-striped">
    <thead>
        <tr>
        <th scope="col">Image</th>
        <th scope="col">Title</th>
        <th scope="col">Source</th>
        <th scope="col">Description</th>
        <th scope="col">Updated</th>
        <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @saved_collection.each do |item| %>
        <tr>
            <td ><img class="img-fluid img-thumbnail" src="https://dp.la/thumb/<%= item.object %>"/><br> <a target="_blank" href="<%= item.sourceLink %>">View Original</a></td>
            <td ><%= item.title %></td>
            <td ><%= item.dataProvider %></td>
            <td ><%= item.description %></td>
            <td ><%= time_ago_in_words(item.updated_at) %> ago</td>
            
            <% if logged_in? %>
            <td ><%= link_to 'Update', user_digital_object_path(object_id: item.object, id: item.id), method: :put, 
                class: 'btn btn-sm btn-info mb-2' %>
            <%= link_to 'Remove', user_digital_object_path(item), method: :delete, data: {confirm: "Are you sure?"},
             class: 'btn btn-sm btn-warning' %></td>
            <% end %> 
        </tr>
        <% end %>
    </tbody>
    </table>

</div>
<% end %>

app/views/digital_objects/_obj_fields.html.erb
<div class='nested-fields mt-2 mb-2 card px-4 py-4 accordion-item'>
  <div class="accordion-header" id="heading-obj-<%= f.object.id %>">
    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#acc-obj-<%= f.object.id %>" aria-expanded="false" aria-controls="acc-obj-<%= f.object.id %>">
      <% if f.object.id %>
        <%= f.object.digital_object.title %> from <%= f.object.digital_object.dataProvider %>
      <% else %>
        New Exhibit Object
      <% end %>
      </button>
  </div>
  <div id="acc-obj-<%= f.object.id %>" class="accordion-collapse collapse" aria-labelledby="heading-obj-<%= f.object.id %>" >
  <div class="accordion-body">
    <%= f.collection_select(:digital_object_id, @digital_objects, :id, :title, { prompt: "Press shift to select multiple options" }, {class: "form-select shadow rounded mb-4" } ) %>
    <div class="field">
      <%= f.label :content, "Exhibit Note", class: "form-label mt-4" %>
      <%= f.rich_text_area :content, class: "form-control" %>
    </div>
      <%= f.hidden_field :object_order, class: "object-order" %>
    <%= link_to_remove_association "Remove object", f, class: "btn btn-outline-danger mt-2" %>
    <script>
      $("#digital_objects").trigger("new_object");
    </script>
    </div>
  </div>
</div>

app/views/digital_objects/show.html.erb
<%= render list %>